export const combinedTeamsSearchMap: Record<string, string[]> = {
  // Belgian Teams
  "Royal Antwerp FC": ["Antwerp", "Royal Antwerp", "RAFC"],
  "Club Brugge KV": ["Club Brugge", "Brugge", "CB"],
  "Cercle Brugge KSV": ["Cercle Brugge", "Cercle", "Cercle Brugge KSV"],
  "KAA Gent": ["Gent", "KAA Gent"],
  "KRC Genk": ["Genk", "KRC Genk"],
  "RSC Anderlecht": ["Anderlecht", "RSCA"],
  "Standard Liège": ["Standard", "Standard Liege", "Standard de Liège"],
  "Union Saint-Gilloise": ["Union", "Union SG", "Saint-Gilloise"],
  "KV Mechelen": ["Mechelen", "KV Mechelen", "Malines"],
  "Sint-Truidense VV": ["Sint-Truiden", "STVV"],
  "Oud-Heverlee Leuven": ["OH Leuven", "Leuven", "Oud-Heverlee"],
  "Charleroi SC": ["Charleroi", "RCSC"],
  "Westerlo": ["Westerlo", "KVC Westerlo"],
  "KAS Eupen": ["Eupen", "KAS Eupen"],
  "KV Kortrijk": ["Kortrijk", "KVK", "KV Kortrijk"],
  "RWDM": ["RWDM", "RWD Molenbeek"],
  "RFC Seraing": ["Seraing", "RFC Seraing"],
  "Lommel SK": ["Lommel", "Lommel SK"],
  "Beerschot VA": ["Beerschot", "Beerschot VA"],
  "Deinze": ["Deinze"],
  "SL16 FC": ["SL16", "SL16 FC"],
  "Club NXT": ["Club NXT", "NXT"],
  "RSCA Futures": ["RSCA Futures", "Anderlecht II"],
  "Lierse Kempenzonen": ["Lierse", "Lierse Kempenzonen"],
  "Dender EH": ["Dender", "Dender EH"],
  "Zulte Waregem": ["Zulte", "Zulte Waregem"],
  "Patro Eisden Maasmechelen": ["Patro Eisden", "Patro", "Patro Eisden Maasmechelen"],

  // English Teams
  "Arsenal FC": ["Arsenal"],
  "Aston Villa FC": ["Aston Villa", "Villa"],
  "AFC Bournemouth": ["Bournemouth", "AFC Bournemouth"],
  "Brentford FC": ["Brentford"],
  "Brighton & Hove Albion FC": ["Brighton", "Brighton & Hove Albion", "Brighton Hove"],
  "Burnley FC": ["Burnley"],
  "Chelsea FC": ["Chelsea"],
  "Crystal Palace FC": ["Crystal Palace", "Palace"],
  "Everton FC": ["Everton"],
  "Fulham FC": ["Fulham"],
  "Liverpool FC": ["Liverpool", "LFC"],
  "Luton Town FC": ["Luton", "Luton Town"],
  "Manchester City FC": ["Manchester City", "Man City", "City"],
  "Manchester United FC": ["Manchester United", "Man United", "Man Utd", "United"],
  "Newcastle United FC": ["Newcastle", "Newcastle United"],
  "Nottingham Forest FC": ["Nottingham Forest", "Forest"],
  "Sheffield United FC": ["Sheffield United", "Sheffield Utd", "Sheff Utd"],
  "Tottenham Hotspur FC": ["Tottenham", "Spurs", "Tottenham Hotspur"],
  "West Ham United FC": ["West Ham", "West Ham United"],
  "Wolverhampton Wanderers FC": ["Wolverhampton", "Wolves", "Wolverhampton Wanderers"],
  "Birmingham City FC": ["Birmingham City", "Birmingham"],
  "Blackburn Rovers FC": ["Blackburn", "Blackburn Rovers"],
  "Bristol City FC": ["Bristol City"],
  "Cardiff City FC": ["Cardiff City", "Cardiff"],
  "Coventry City FC": ["Coventry", "Coventry City"],
  "Huddersfield Town AFC": ["Huddersfield", "Huddersfield Town"],
  "Hull City AFC": ["Hull", "Hull City"],
  "Ipswich Town FC": ["Ipswich", "Ipswich Town"],
  "Leeds United FC": ["Leeds", "Leeds United"],
  "Leicester City FC": ["Leicester", "Leicester City"],
  "Middlesbrough FC": ["Middlesbrough", "Boro"],
  "Millwall FC": ["Millwall"],
  "Norwich City FC": ["Norwich", "Norwich City"],
  "Plymouth Argyle FC": ["Plymouth", "Plymouth Argyle"],
  "Preston North End FC": ["Preston", "Preston North End"],
  "Queens Park Rangers FC": ["QPR", "Queens Park Rangers"],
  "Rotherham United FC": ["Rotherham", "Rotherham United"],
  "Sheffield Wednesday FC": ["Sheffield Wednesday", "Sheff Wed"],
  "Southampton FC": ["Southampton", "Saints"],
  "Stoke City FC": ["Stoke", "Stoke City"],
  "Sunderland AFC": ["Sunderland"],
  "Swansea City AFC": ["Swansea", "Swansea City"],
  "Watford FC": ["Watford"],
  "West Bromwich Albion FC": ["West Brom", "West Bromwich Albion"],

  // German Teams
  "Bayer 04 Leverkusen": ["Bayer Leverkusen", "Leverkusen", "B04"],
  "FC Bayern München": ["Bayern München", "Bayern Munich", "Bayern"],
  "Borussia Dortmund": ["Dortmund", "BVB", "Borussia Dortmund"],
  "RB Leipzig": ["RB Leipzig", "Leipzig"],
  "VfB Stuttgart": ["Stuttgart", "VfB Stuttgart"],
  "Eintracht Frankfurt": ["Eintracht Frankfurt", "Frankfurt"],
  "TSG 1899 Hoffenheim": ["Hoffenheim", "TSG Hoffenheim"],
  "Werder Bremen": ["Werder Bremen", "Bremen"],
  "SC Freiburg": ["Freiburg", "SC Freiburg"],
  "VfL Wolfsburg": ["Wolfsburg", "VfL Wolfsburg"],
  "1. FC Heidenheim": ["Heidenheim", "1. FC Heidenheim"],
  "FC Augsburg": ["Augsburg", "FC Augsburg"],
  "Borussia Mönchengladbach": ["Mönchengladbach", "Gladbach", "Borussia M'gladbach"],
  "1. FC Union Berlin": ["Union Berlin", "Union"],
  "VfL Bochum": ["Bochum", "VfL Bochum"],
  "1. FSV Mainz 05": ["Mainz", "Mainz 05", "FSV Mainz"],
  "1. FC Köln": ["Köln", "Cologne", "1. FC Köln"],
  "SV Darmstadt 98": ["Darmstadt", "SV Darmstadt"],
  "FC St. Pauli": ["St. Pauli", "FC St. Pauli"],
  "Holstein Kiel": ["Kiel", "Holstein Kiel"],
  "Fortuna Düsseldorf": ["Düsseldorf", "Fortuna Düsseldorf"],
  "Hamburger SV": ["Hamburg", "HSV", "Hamburger SV"],
  "Karlsruher SC": ["Karlsruhe", "Karlsruher SC"],
  "Hannover 96": ["Hannover", "Hannover 96"],
  "SC Paderborn 07": ["Paderborn", "SC Paderborn"],
  "Hertha BSC": ["Hertha", "Hertha BSC", "Berlin"],
  "SpVgg Greuther Fürth": ["Greuther Fürth", "Fürth"],
  "1. FC Nürnberg": ["Nürnberg", "Nurnberg", "1. FC Nürnberg"],
  "1. FC Kaiserslautern": ["Kaiserslautern", "1. FC Kaiserslautern"],
  "Eintracht Braunschweig": ["Braunschweig", "Eintracht Braunschweig"],
  "Hansa Rostock": ["Rostock", "Hansa Rostock"],
  "SV Elversberg": ["Elversberg", "SV Elversberg"],
  "1. FC Magdeburg": ["Magdeburg", "1. FC Magdeburg"],
  "VfL Osnabrück": ["Osnabrück", "VfL Osnabrück"],
  "Schalke 04": ["Schalke", "Schalke 04"],
  "SV Wehen Wiesbaden": ["Wiesbaden", "SV Wehen", "Wehen Wiesbaden"],

  // Spanish Teams
  "Real Madrid": ["Real Madrid CF", "Madrid", "RM"],
  "Barcelona": ["FC Barcelona", "Barça", "FCB"],
  "Atlético Madrid": ["Atlético Madrid", "Atletico", "Atleti"],
  "Girona FC": ["Girona", "Girona FC"],
  "Athletic Club": ["Athletic Club", "Athletic Bilbao", "Bilbao"],
  "Real Sociedad": ["Real Sociedad", "Sociedad"],
  "Real Betis": ["Betis", "Real Betis"],
  "Valencia CF": ["Valencia", "Valencia CF"],
  "Villarreal CF": ["Villarreal", "Villarreal CF", "Submarino Amarillo"],
  "Getafe CF": ["Getafe", "Getafe CF"],
  "Sevilla FC": ["Sevilla", "Sevilla FC"],
  "Rayo Vallecano": ["Rayo", "Rayo Vallecano"],
  "CA Osasuna": ["Osasuna", "CA Osasuna"],
  "Deportivo Alavés": ["Alavés", "Deportivo Alavés"],
  "UD Las Palmas": ["Las Palmas", "UD Las Palmas"],
  "RCD Mallorca": ["Mallorca", "RCD Mallorca"],
  "Celta de Vigo": ["Celta", "Celta de Vigo"],
  "Cádiz CF": ["Cádiz", "Cadiz", "Cádiz CF"],
  "Granada CF": ["Granada", "Granada CF"],
  "UD Almería": ["Almería", "UD Almería"],
  "Real Valladolid": ["Valladolid", "Real Valladolid"],
  "Eibar": ["Eibar", "SD Eibar"],
  "RCD Espanyol de Barcelona": ["Espanyol", "RCD Espanyol"],
  "Sporting Gijón": ["Sporting Gijón", "Gijón", "Sporting"],
  "Real Oviedo": ["Oviedo", "Real Oviedo"],
  "Levante UD": ["Levante", "Levante UD"],
  "Burgos CF": ["Burgos", "Burgos CF"],
  "Elche CF": ["Elche", "Elche CF"],
  "CD Eldense": ["Eldense", "CD Eldense"],
  "CD Tenerife": ["Tenerife", "CD Tenerife"],
  "Real Zaragoza": ["Zaragoza", "Real Zaragoza"],
  "Racing Santander": ["Racing", "Racing Santander"],
  "FC Cartagena": ["Cartagena", "FC Cartagena"],
  "Albacete Balompié": ["Albacete", "Albacete Balompié"],
  "Huesca": ["Huesca", "SD Huesca"],
  "Villarreal B": ["Villarreal B", "Villarreal II"],
  "AD Alcorcón": ["Alcorcón", "AD Alcorcón"],
  "Mirandés": ["Mirandés", "CD Mirandés"],
  "Amorebieta": ["Amorebieta", "SD Amorebieta"],
  "FC Andorra": ["Andorra", "FC Andorra"],

  // Italian Teams
  "Juventus FC": ["Juventus", "Juve", "Juventus FC"],
  "AC Milan": ["Milan", "AC Milan", "Rossoneri"],
  "Inter Milan": ["Inter", "Inter Milan", "Nerazzurri"],
  "AS Roma": ["Roma", "AS Roma", "Giallorossi"],
  "SSC Napoli": ["Napoli", "SSC Napoli"],
  "Lazio": ["Lazio", "SS Lazio", "Biancocelesti"],
  "Atalanta Bergamasca Calcio": ["Atalanta", "Atalanta Bergamasca", "La Dea"],
  "ACF Fiorentina": ["Fiorentina", "ACF Fiorentina", "Viola"],
  "Sampdoria": ["Sampdoria", "UC Sampdoria"],
  "Torino FC": ["Torino", "Torino FC"],
  "Bologna FC": ["Bologna", "Bologna FC"],
  "Udinese Calcio": ["Udinese", "Udinese Calcio"],
  "Empoli FC": ["Empoli", "Empoli FC"],
  "Spezia Calcio": ["Spezia", "Spezia Calcio"],
  "Monza": ["Monza", "AC Monza"],
  "Salernitana": ["Salernitana", "US Salernitana"],
  "Lecce": ["Lecce", "US Lecce"],
  "Verona": ["Verona", "Hellas Verona", "Hellas"],
  "Cagliari Calcio": ["Cagliari", "Cagliari Calcio"],
  "Parma Calcio": ["Parma", "Parma Calcio", "Gialloblu"],
  "Brescia Calcio": ["Brescia", "Brescia Calcio"],
  "Pisa SC": ["Pisa", "Pisa SC"],
  "Cittadella": ["Cittadella", "AS Cittadella"],
  "Frosinone Calcio": ["Frosinone", "Frosinone Calcio"],
  "Pescara Calcio": ["Pescara", "Pescara Calcio"],
  "Cosenza Calcio": ["Cosenza", "Cosenza Calcio"],
  "Reggina Calcio": ["Reggina", "Reggina Calcio"],
  "Perugia Calcio": ["Perugia", "Perugia Calcio"],
  "Venezia FC": ["Venezia", "Venezia FC"],
  "Ascoli Calcio": ["Ascoli", "Ascoli Calcio"],
  "Vicenza Calcio": ["Vicenza", "Vicenza Calcio"],
  "Alessandria Calcio": ["Alessandria", "Alessandria Calcio"],
  "Cremonese": ["Cremonese", "US Cremonese"],
  "Ternana Calcio": ["Ternana", "Ternana Calcio"],
  "Benevento Calcio": ["Benevento", "Benevento Calcio"],
  "SPAL": ["SPAL", "SPAL Ferrara", "Società Pol. Ars et Labor"],
  "Foggia Calcio": ["Foggia", "Foggia Calcio"],
  "Reggiana": ["Reggiana", "AC Reggiana 1919"],

  // Dutch Teams
  "Ajax Amsterdam": ["Ajax", "Amsterdami Ajax", "Ajax Amsterdam", "Ajacieden"],
  "PSV Eindhoven": ["PSV", "PSV Eindhoven", "Boeren"],
  "Feyenoord Rotterdam": ["Feyenoord", "Feyenoord Rotterdam", "De Kuip"],
  "AZ Alkmaar": ["AZ", "AZ Alkmaar", "Alkmaar"],
  "Vitesse Arnhem": ["Vitesse", "Vitesse Arnhem"],
  "FC Utrecht": ["Utrecht", "FC Utrecht"],
  "FC Groningen": ["Groningen", "FC Groningen"],
  "SC Heerenveen": ["Heerenveen", "SC Heerenveen"],
  "Willem II": ["Willem II", "Willem II Tilburg"],
  "FC Twente": ["Twente", "FC Twente"],
  "Heracles Almelo": ["Heracles", "Heracles Almelo"],
  "PEC Zwolle": ["PEC Zwolle", "Zwolle"],
  "Sparta Rotterdam": ["Sparta", "Sparta Rotterdam"],
  "RKC Waalwijk": ["RKC", "RKC Waalwijk"],
  "FC Emmen": ["Emmen", "FC Emmen"],
  "Fortuna Sittard": ["Fortuna", "Fortuna Sittard"],
  "FC Volendam": ["Volendam", "FC Volendam"],
  "FC Eindhoven": ["Eindhoven", "FC Eindhoven"],
  "Go Ahead Eagles": ["Go Ahead", "Go Ahead Eagles"],
  "Almere City FC": ["Almere City", "Almere City FC"],
  "NEC Nijmegen": ["NEC", "NEC Nijmegen"],
  "Dordrecht": ["Dordrecht", "FC Dordrecht"],
  "FC Den Bosch": ["Den Bosch", "FC Den Bosch"],
  "Telstar": ["Telstar", "SC Telstar"],
  "MVV Maastricht": ["MVV", "MVV Maastricht"],
  "Helmond Sport": ["Helmond Sport", "Helmond"],
  "Jong Ajax": ["Jong Ajax", "Ajax II"],
  "Jong PSV": ["Jong PSV", "PSV II"],
  "Jong Utrecht": ["Jong Utrecht", "Utrecht II"],
  "Jong FC Groningen": ["Jong Groningen", "Groningen II"],
  "Jong AZ": ["Jong AZ", "AZ II"],
  "Jong Heerenveen": ["Jong Heerenveen", "Heerenveen II"],
  "Jong Vitesse": ["Jong Vitesse", "Vitesse II"],

  // French Teams
  "Paris Saint-Germain": ["PSG", "Paris", "Paris Saint-Germain"],
  "Olympique Lyonnais": ["Lyon", "OL", "Olympique Lyonnais"],
  "Olympique de Marseille": ["Marseille", "OM", "Olympique Marseille"],
  "AS Monaco": ["Monaco", "AS Monaco"],
  "Lille OSC": ["Lille", "Lille OSC"],
  "OGC Nice": ["Nice", "OGC Nice"],
  "RC Lens": ["Lens", "RC Lens"],
  "Montpellier HSC": ["Montpellier", "MHSC", "Montpellier HSC"],
  "Stade Rennais FC": ["Rennes", "Stade Rennais", "Rennes FC"],
  "FC Nantes": ["Nantes", "FC Nantes"],
  "Bordeaux": ["Bordeaux", "Girondins de Bordeaux"],
  "AS Saint-Étienne": ["Saint-Étienne", "ASSE", "ASSE Saint-Étienne"],
  "Angers SCO": ["Angers", "Angers SCO"],
  "Strasbourg": ["Strasbourg", "RC Strasbourg Alsace"],
  "Troyes AC": ["Troyes", "ES Troyes AC"],
  "Clermont Foot": ["Clermont", "Clermont Foot 63"],
  "Lorient": ["Lorient", "FC Lorient"],
  "Ajaccio": ["Ajaccio", "AC Ajaccio"],
  "Reims": ["Reims", "Stade de Reims"],
  "Sochaux": ["Sochaux", "FC Sochaux-Montbéliard"],
  "Chamois Niortais": ["Niort", "Chamois Niortais"],
  "GFC Ajaccio": ["GFC Ajaccio", "Gazélec Ajaccio"],
  "Paris FC": ["Paris FC", "Paris"],
  "Valenciennes": ["Valenciennes", "VAFC"],
  "Nancy": ["Nancy", "AS Nancy"],
  "Le Havre": ["Le Havre", "Le Havre AC"],
  "Brest": ["Brest", "Stade Brestois"],
  "Le Mans": ["Le Mans", "Le Mans FC"],
  "Tours": ["Tours", "Tours FC"],
  "Amiens": ["Amiens", "Amiens SC"],
  "Dijon": ["Dijon", "Dijon FCO"],
  "Quevilly-Rouen": ["Quevilly", "Quevilly-Rouen Métropole"],
  "Caen": ["Caen", "SM Caen"],

  // Portuguese Teams
  "Benfica": ["Benfica", "SL Benfica"],
  "Porto": ["Porto", "FC Porto"],
  "Sporting CP": ["Sporting", "Sporting CP"],
  "Braga": ["Braga", "SC Braga"],
  "Belenenses SAD": ["Belenenses", "Belenenses SAD"],
  "Vitoria SC": ["Guimaraes", "Vitoria Guimaraes", "Vitoria SC"],
  "Maritimo": ["Maritimo", "CD Maritimo"],
  "Santa Clara": ["Santa Clara", "CD Santa Clara"],
  "Boavista": ["Boavista", "Boavista FC"],
  "Gil Vicente": ["Gil Vicente", "Gil Vicente FC"],
  "Tondela": ["Tondela", "CD Tondela"],
  "Famalicao": ["Famalicao", "FC Famalicao"],
  "Moreirense": ["Moreirense", "Moreirense FC"],
  "Nacional": ["Nacional", "CD Nacional"],
  "Estoril Praia": ["Estoril", "Estoril Praia"],
  "Arouca": ["Arouca", "FC Arouca"],
  "Académica de Coimbra": ["Academica", "Academica de Coimbra"],
  "Leixões SC": ["Leixoes", "Leixões SC"],
  "Cova da Piedade": ["Cova da Piedade", "Cova da Piedade"],
  "Vilafranquense": ["Vilafranquense", "Vilafranquense FC"],
  "Casa Pia": ["Casa Pia", "Casa Pia AC"],
  "Olhanense": ["Olhanense", "SC Olhanense"],
  "Fafe": ["Fafe", "AD Fafe"],
  "Portimonense": ["Portimonense", "Portimonense SC"],
  "Varzim SC": ["Varzim", "Varzim SC"],
  "Canelas 2010": ["Canelas", "Canelas 2010"],
  "União da Madeira": ["União Madeira", "União da Madeira"],
  "CD Mafra": ["Mafra", "CD Mafra"],

  // Turkish Teams
  "Galatasaray": ["Galatasaray", "GS", "Galatasaray SK"],
  "Fenerbahçe": ["Fenerbahce", "Fenerbahce SK"],
  "Beşiktaş": ["Besiktas", "Besiktas JK"],
  "Trabzonspor": ["Trabzonspor", "Trabzon", "TS"],
  "Başakşehir": ["Basaksehir", "Başakşehir FK"],
  "Göztepe": ["Goztepe", "Göztepe SK"],
  "Sivasspor": ["Sivasspor", "Demir Grup Sivasspor"],
  "Antalyaspor": ["Antalyaspor", "Antalya", "Antalyaspor A.Ş."],
  "Kasımpaşa": ["Kasimpasa", "Kasımpaşa SK"],
  "Çaykur Rizespor": ["Rizespor", "Çaykur Rizespor"],
  "Alanyaspor": ["Alanyaspor", "Alanyaspor A.Ş."],
  "Konya": ["Konya", "Konyaspor", "Atiker Konyaspor"],
  "Yeni Malatyaspor": ["Malatyaspor", "Yeni Malatyaspor", "Malatya"],
  "Fatih Karagümrük": ["Karagumruk", "Fatih Karagümrük"],
  "Ankaragücü": ["Ankaragucu", "Ankaragücü"],
  "Adanaspor": ["Adanaspor", "Adanaspor A.Ş."],
  "Ümraniyespor": ["Umraniyespor", "Ümraniyespor"],
  "Manisa FK": ["Manisa", "Manisa FK"],
  "Altay": ["Altay", "Altay SK"],
  "Bandırmaspor": ["Bandirmaspor", "Bandırmaspor"],
  "Büyükşehir Belediye Erzurumspor": ["Erzurumspor", "BB Erzurumspor"],
  "Boluspor": ["Boluspor", "Boluspor A.Ş."],
  "İstanbulspor": ["Istanbulspor", "Istanbulspor A.Ş."],
  "Giresunspor": ["Giresunspor", "Giresunspor A.Ş."],
  "Samsunspor": ["Samsunspor", "Samsunspor A.Ş."],
  "Keçiörengücü": ["Keciorengucu", "Keçiörengücü"],
  "Kocaelispor": ["Kocaelispor", "Kocaelispor A.Ş."],
  "Menemenspor": ["Menemenspor", "Menemenspor A.Ş."],
  "Denizlispor": ["Denizlispor", "Denizlispor A.Ş."],
  "Adana Demirspor": ["Adana Demirspor", "Adana Demirspor A.Ş."],

  "Bayern München": ["Bayern Munich", "Bayern", "FC Bayern", "Bayerns"],
  "Liverpool": ["Liverpool", "The Reds", "LFC"],
  "Manchester City": ["Man City", "Manchester City", "City", "The Citizens"],
  "Chelsea": ["Chelsea", "The Blues", "CFC"],
  "Juventus": ["Juventus", "Juve", "La Vecchia Signora"],
  "Manchester United": ["Man United", "Manchester United", "Red Devils"],
  "Atletico Madrid": ["Atletico Madrid", "Atleti", "Los Colchoneros"],
  "Arsenal": ["Arsenal", "The Gunners", "AFC"],
  "Tottenham Hotspur": ["Tottenham", "Spurs", "Tottenham Hotspur FC"],
  "FC Porto": ["Porto", "FC Porto", "Dragões"],
  "Ajax": ["Ajax", "AFC Ajax", "Amsterdammers"],
  "Napoli": ["Napoli", "SSC Napoli", "Partenopei"],
  "Lyon": ["Lyon", "Olympique Lyonnais", "Les Gones"],
  "Bayer Leverkusen": ["Leverkusen", "Bayer Leverkusen", "Die Werkself"],
  "Sevilla": ["Sevilla", "Sevilla FC", "Los Nervionenses"],
  "Shakhtar Donetsk": ["Shakhtar", "Shakhtar Donetsk", "Miners"],
  "Zenit St. Petersburg": ["Zenit", "Zenit St. Petersburg", "Zénith"],
  "Dynamo Kyiv": ["Dynamo Kyiv", "Dynamo", "FC Dynamo Kyiv"],
  "Club Brugge": ["Club Brugge", "Brugge", "Blauw-Zwart"],
  "Red Bull Salzburg": ["Salzburg", "Red Bull Salzburg", "Die Bullen"],
  "Feyenoord": ["Feyenoord", "Feyenoord Rotterdam", "De club aan de Maas"],
  "Celtic": ["Celtic", "Celtic FC", "The Bhoys"],
  "BSC Young Boys": ["Young Boys", "BSC Young Boys", "YB"],
  "Lille": ["Lille", "LOSC Lille", "Les Dogues"]
};


export const teamFromFootballApi = [
  "RC Strasbourg Alsace",
  "AS Saint-Étienne",
  "Le Havre AC",
  "AS Monaco FC",
  "Olympique Lyonnais",
  "Stade Rennais FC 1901",
  "Fortuna Sittard",
  "Willem II Tilburg",
  "AFC Ajax",
  "Sparta Rotterdam",
  "SC Heerenveen",
  "NEC",
  "Angers SCO",
  "Lille OSC",
  "Villarreal CF",
  "RCD Espanyol de Barcelona",
  "Almere City FC",
  "Go Ahead Eagles",
  "FC Nantes",
  "Toulouse FC",
  "Montpellier HSC",
  "Stade de Reims",
  "Racing Club de Lens",
  "AJ Auxerre",
  "Olympique de Marseille",
  "Stade Brestois 29",
  "Rayo Vallecano de Madrid",
  "Getafe CF",
  "Deportivo Alavés",
  "Club Atlético de Madrid",
  "CA Osasuna",
  "UD Las Palmas",
  "Valencia CF",
  "Heracles Almelo",
  "Feyenoord Rotterdam",
  "FC Groningen",
  "RKC Waalwijk",
  "Real Madrid CF",
  "RC Celta de Vigo",
  "PSV",
  "NAC Breda",
  "PEC Zwolle",
  "Real Valladolid CF",
  "FC Barcelona",
  "AZ",
  "FC Twente '65",
  "Sevilla FC",
  "CD Leganés",
  "Real Betis Balompié",
  "Real Sociedad de Fútbol",
  "Athletic Club",
  "Girona FC",
  "RCD Mallorca",
  "CD Santa Clara",
  "FC Arouca",
  "Gil Vicente FC",
  "SC Farense",
  "CF Estrela da Amadora",
  "FC Porto",
  "Moreirense FC",
  "CD Nacional",
  "Sport Lisboa e Benfica",
  "AVS",
  "Vitória Guimarães",
  "Rio Ave FC",
  "Boavista FC",
  "Sporting Clube de Portugal",
  "Casa Pia AC",
  "GD Estoril Praia",
  "FC Famalicão",
  "Sporting Clube de Braga",
  "Como 1907",
  "Genoa CFC",
  "FC Internazionale Milano",
  "AS Roma",
  "SS Lazio",
  "Parma Calcio 1913",
  "Venezia FC",
  "AC Milan",
  "ACF Fiorentina",
  "Empoli FC",
  "Juventus FC",
  "AC Monza",
  "SSC Napoli",
  "Torino FC",
  "Udinese Calcio",
  "Bologna FC 1909",
  "Hellas Verona FC",
  "Cagliari Calcio",
  "US Lecce",
  "Atalanta BC",
  "Sivasspor",
  "Antalyaspor",
  "Beşiktaş",
  "Hatayspor",
  "Kayserispor",
  "Çaykur Rizespor",
  "Konyaspor",
  "Adana Demirspor",
  "Trabzonspor",
  "Alanyaspor",
  "Eyüpspor",
  "Galatasaray",
  "Bodrum FK",
  "Samsunspor",
  "Göztepe",
  "İstanbul Başakşehir",
  "Gaziantep FK",
  "Fenerbahçe",
  "Kasımpaşa SK",
  "Arsenal FC (ENG)",
  "Paris Saint-Germain FC (FRA)",
  "FC Barcelona (ESP)",
  "FC Internazionale Milano (ITA)",
  "FC Utrecht",
  "OGC Nice",
  "Paris Saint-Germain FC",
  "Luton Town FC",
  "Coventry City FC",
  "Queens Park Rangers FC",
  "Burnley FC",
  "Chelsea FC",
  "Everton FC",
  "Blackburn Rovers FC",
  "Watford FC",
  "Cardiff City FC",
  "West Bromwich Albion FC",
  "Hull City AFC",
  "Derby County FC",
  "Middlesbrough FC",
  "Norwich City FC",
  "Millwall FC",
  "Swansea City AFC",
  "Oxford United FC",
  "Sunderland AFC",
  "Preston North End FC",
  "Plymouth Argyle FC",
  "Sheffield Wednesday FC",
  "Portsmouth FC",
  "Brighton & Hove Albion FC",
  "West Ham United FC",
  "Newcastle United FC",
  "Ipswich Town FC",
  "Southampton FC",
  "Fulham FC",
  "Wolverhampton Wanderers FC",
  "Leicester City FC",
  "TSG 1899 Hoffenheim",
  "Borussia Dortmund",
  "VfL Wolfsburg",
  "SC Freiburg",
  "FC Bayern München",
  "1. FSV Mainz 05",
  "Holstein Kiel",
  "Borussia Mönchengladbach",
  "Bayer 04 Leverkusen",
  "FC Augsburg",
  "Oud-Heverlee Leuven",
  "Standard Liège",
  "KVC Westerlo",
  "KV Mechelen",
  "Eintracht Frankfurt",
  "RB Leipzig",
  "Sporting Charleroi",
  "FCV Dender EH",
  "Cercle Brugge",
  "Sint-Truidense VV",
  "KAA Gent",
  "RSC Anderlecht",
  "AFC Bournemouth",
  "Manchester United FC",
  "VfL Bochum 1848",
  "1. FC Union Berlin",
  "KRC Genk",
  "Royal Antwerp FC",
  "Liverpool FC",
  "Tottenham Hotspur FC",
  "SV Werder Bremen",
  "FC St. Pauli 1910",
  "Union Saint-Gilloise",
  "Club Brugge KV",
  "Leeds United FC",
  "Bristol City FC",
  "Nottingham Forest FC",
  "Brentford FC",
  "Manchester City FC",
  "1. FC Heidenheim 1846",
  "Stoke City FC",
  "Sheffield United FC",
  "Aston Villa FC",
  "VfB Stuttgart",
  "KV Kortrijk",
  "Arsenal FC",
  "K Beerschot VA",
  "Crystal Palace FC",
  "N.N."
]

// Key TV value API

export const pairedTeams = {
  "Arsenal": "Arsenal FC",
  "Aston Villa": "Aston Villa FC",
  "Atalanta": "Atalanta BC",
  "Athletic Club": "Athletic Club",
  "Atlético Madrid": "Club Atlético de Madrid",
  "Augsburg": "FC Augsburg",
  "Barcelona": "FC Barcelona",
  "Bayern München": "FC Bayern München",
  "Benfica": "Sport Lisboa e Benfica",
  "Besiktas": "Beşiktaş",
  "Boavista": "Boavista FC",
  "Bochum": "VfL Bochum 1848",
  "Bologna": "Bologna FC 1909",
  "Bournemouth": "AFC Bournemouth",
  "Braga": "Sporting Clube de Braga",
  "Brentford": "Brentford FC",
  "Brighton & Hove Albion": "Brighton & Hove Albion FC",
  "CA Osasuna": "CA Osasuna",
  "Casa Pia": "Casa Pia AC",
  "Chelsea": "Chelsea FC",
  "Crystal Palace": "Crystal Palace FC",
  "Deportivo Alavés": "Deportivo Alavés",
  "Dortmund": "Borussia Dortmund",
  "Düsseldorf": "Fortuna Düsseldorf",
  "Eintracht Frankfurt": "Eintracht Frankfurt",
  "Empoli": "Empoli FC",
  "Estoril": "GD Estoril Praia",
  "Everton": "Everton FC",
  "FC Barcelona": "FC Barcelona",
  "FC Porto": "FC Porto",
  "Fenerbahce": "Fenerbahçe",
  "Fiorentina": "ACF Fiorentina",
  "Frankfurt": "Eintracht Frankfurt",
  "Freiburg": "SC Freiburg",
  "Fulham": "Fulham FC",
  "Galatasaray": "Galatasaray",
  "Getafe CF": "Getafe CF",
  "Gil Vicente": "Gil Vicente FC",
  "Girona FC": "Girona FC",
  "Heidenheim": "1. FC Heidenheim 1846",
  "Hoffenheim": "TSG 1899 Hoffenheim",
  "Inter": "FC Internazionale Milano",
  "Ipswich": "Ipswich Town FC",
  "Juventus": "Juventus FC",
  "Kiel": "Holstein Kiel",
  "Lazio": "SS Lazio",
  "Lecce": "US Lecce",
  "Leicester City": "Leicester City FC",
  "Leverkusen": "Bayer 04 Leverkusen",
  "Liverpool": "Liverpool FC",
  "Mainz": "1. FSV Mainz 05",
  "Mallorca": "RCD Mallorca",
  "Manchester City": "Manchester City FC",
  "Manchester United": "Manchester United FC",
  "Milan": "AC Milan",
  "Monza": "AC Monza",
  "Moreirense": "Moreirense FC",
  "Mönchengladbach": "Borussia Mönchengladbach",
  "Napoli": "SSC Napoli",
  "Newcastle": "Newcastle United FC",
  "Newcastle United": "Newcastle United FC",
  "Nottingham Forest": "Nottingham Forest FC",
  "PSG": "Paris Saint-Germain FC",
  "Parma": "Parma Calcio 1913",
  "RB Leipzig": "RB Leipzig",
  "RCD Espanyol": "RCD Espanyol de Barcelona",
  "RCD Mallorca": "RCD Mallorca",
  "Rayo Vallecano": "Rayo Vallecano de Madrid",
  "Real Betis": "Real Betis Balompié",
  "Real Madrid": "Real Madrid CF",
  "Real Sociedad": "Real Sociedad de Fútbol",
  "Real Valladolid": "Real Valladolid CF",
  "Roma": "AS Roma",
  "Sevilla FC": "Sevilla FC",
  "Sivasspor": "Sivasspor",
  "Southampton": "Southampton FC",
  "Sporting": "Sporting Clube de Portugal",
  "St. Pauli": "FC St. Pauli 1910",
  "Torino": "Torino FC",
  "Tottenham Hotspur": "Tottenham Hotspur FC",
  "UD Las Palmas": "UD Las Palmas",
  "Udinese": "Udinese Calcio",
  "Union Berlin": "1. FC Union Berlin",
  "Valencia CF": "Valencia CF",
  "Venezia": "Venezia FC",
  "Verona": "Hellas Verona FC",
  "Villarreal CF": "Villarreal CF",
  "Werder Bremen": "SV Werder Bremen",
  "West Ham United": "West Ham United FC",
  "Wolfsburg": "VfL Wolfsburg",
  "Wolverhampton": "Wolverhampton Wanderers FC",
  "Wolverhampton Wanderers": "Wolverhampton Wanderers FC"
}